[package]
name = "hubgt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-play = "0.5.1"
http = "1.0.0"
reqwest = "0.11.22"
